### ISSUE TITLE
Why RavenManager?

### ISSUE THREAD

**Issue by JudahGabriel** [FriendlyAgent/RavenDB.AspNetCore.DependencyInjection#3]
Can you explain the reason to have RavenManager? It appears you want to support multiple distinct DocumentStores.

I've never built an app that requires more than one cluster. Either my app uses a single database, or has a cluster of databases. Either way it's a single DocumentStore.

What's the usage scenario for RavenManager?

**Comment by FriendlyAgent** [comment]
The reason for the RavenManager is as you stated, to support multiple distinct DocumentStores.

I've also mostly never use more than one cluster or multiple databases for the majority of my applications. However, there are usage scenarios for having multiple DocumentStores. For example having multiple applications that share data by reading/writing to a common database. In this cause neither applications have ownership of the database and a good separation is needed. 

This is an approach i have used in the past to manage tasks/jobs. Having multiple instances of the same applications(Each with there own database/cluster) sending tasks/jobs to a shared database and having a second different application awaiting/observing this database for a task/job it needs to execute. (In this cause the application handling tasks/jobs has no access tot the database/cluster of the applications creating them)

On a side note I added support to bypass the RavenMananger. You're now able to just inject a DocumentStore using the "AddRavenStore" method instead of "AddRavenMananger". So you now have a lightweight option if you only have one store, which admittedly is most of the time. (I will be updating the documentation when i have a bit more time.)

**Comment by JudahGabriel** [comment]
OK, fair enough, thanks for the explanation.

Speaking of clusters, we don't really have support for that now, do we? We only support a single URL in app settings. May I suggest we support .Urls, and not just .Url, in app settings?
